###############################################
# MoveIt Servo config for tipard_ur20
###############################################

use_gazebo: false

## Incoming joystick-style commands
command_in_type: "unitless"

scale:
  linear: 0.60
  rotational: 0.50
  joint: 0.50

## Outgoing commands
publish_period: 0.034
low_latency_mode: false

command_out_type: trajectory_msgs/JointTrajectory

publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

# demo.launch.py already runs move_group, so Servo should not be the primary planning scene monitor
is_primary_planning_scene_monitor: false

## MoveIt properties
move_group_name: ur_manipulator
planning_frame: ur20_base_link

## Frames
ee_frame_name: tool0
robot_link_command_frame: ur20_base_link

## Stopping behaviour
incoming_command_timeout: 0.1
num_outgoing_halt_msgs_to_publish: 4

## Singularity / joint limit handling
lower_singularity_threshold: 17.0
hard_stop_singularity_threshold: 30.0
joint_limit_margin: 0.1
leaving_singularity_threshold_multiplier: 2.0

## Topics
cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states
status_topic: ~/status
command_out_topic: /ur_manipulator_controller/joint_trajectory

## Collision checking
check_collisions: true
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
