stereo_sync_node:
  ros__parameters:
    use_sim_time: true
    left_image_topic: /rgb_static_2
    right_image_topic: /rgb_static_1
    left_info_topic: /static_camera_info_1
    right_info_topic: /static_camera_info_2
    left_camera_frame: static_camera_1
    right_camera_frame: static_camera_2
    sync_slop: 0.05
    queue_size: 10

disparity_node:
  ros__parameters:
    use_sim_time: true
    ffm_dir: /home/workstation/Fast-FoundationStereo
    model_dir: /home/workstation/Fast-FoundationStereo/weights/23-36-37/model_best_bp2_serialize.pth
    scale: 1.0
    valid_iters: 8
    max_disp: 192
    # |Z_camera_box_1 - Z_camera_box_2| = |1.29487 - 1.23819| = 0.05668 m
    baseline_m: 0.05668

segmentation_node:
  ros__parameters:
    use_sim_time: true
    model_path: /home/workstation/oskar/2025-transformers-for-apple-flower-segmentation-bhangale/experiments/training_outputs/maskrcnn/test_batch/best_hp_run/finetune/model_final.pth
    confidence_threshold: 0.3
    device: cuda

depth_fusion_node:
  ros__parameters:
    use_sim_time: true
    left_info_topic: /rgb_camera_1/camera_info
    erosion_radius_px: 3
    depth_std_threshold: 0.15
    min_valid_pixels: 5

backprojection_node:
  ros__parameters:
    use_sim_time: true
    camera_frame: static_camera_1
    map_frame: map

multiview_fusion_node:
  ros__parameters:
    use_sim_time: true
    eps: 0.08
    min_samples: 3
    window_m: 4.0
    max_age_s: 30.0

bio_sanity_node:
  ros__parameters:
    use_sim_time: true
    expected_flowers_per_corymb: 5
    intra_flower_spacing_m: 0.03
    merge_distance_m: 0.02
    corymb_radius_m: 0.06

tree_assignment_node:
  ros__parameters:
    use_sim_time: true
    tree_map_file: config/tree_map_sim.yaml
    max_radius_m: 0.8

thinning_decision_node:
  ros__parameters:
    use_sim_time: true
    target_flowers_per_tree: 20
    agronomic_min: 15
    agronomic_max: 25
